terraform/modules/tor/cloud-init/tor.yaml

see https://github.com/Blockstream/esplora/issues/36

increase tor performance

---

contrib/nginx.conf.in
contrib/supervisord.conf.in
run.sh

this allows to pass verbose to run.sh as a parameter to get nginx and electrs debug enabled

add debug mode

---

Dockerfile.deps

~~We should wait for stable releases but this branch/PR was useful to test out if we needed any other change to update (so far doesn't seems like it)~~

update core to 0.18.0 and liquid to elements.0.17.0

---

README.md

Fixed electrum port typo

---

build.sh

changed cp flag in build.sh -rL to -RL so it works in mac

changed cp flag

---

.dockerignore
Dockerfile
Dockerfile.deps
client/src/app.js
client/src/driver/blinding.js
client/src/driver/route.js
client/src/lib/libwally.js
client/src/run-browser.js
client/src/run-server.js
client/src/util.js
client/src/views/tx-vin.js
client/src/views/tx-vout.js
client/src/views/tx.js
www/style.css

Blinded commitment verification

---

LICENSE

[trivial] update license to 2021

---

client/src/views/footer.js
client/src/views/nav-toggle.js
flavors/liquid-mainnet/extras.css
www/style.css

- Add "word-break" to Asset List table row
- Move Language Switch to Footer
- Adjust table row padding
- Reduce loading gif size

Move lang switcher footer

---

Dockerfile.deps

https://github.com/elementsproject/elements/releases

bump elements to 0.18.1.12

---

contrib/liquid-testnet-explorer.conf.in

synced from liquidtestnet.com's example

update the liquid-testnet parameters

---

.gitlab-ci.yml
Dockerfile.deps
Dockerfile.tor
contrib/0001-add-support-to-save-fee-estimates-without-shutting-d.patch
contrib/nginx-sync.conf.in
run.sh

@shesek mind reviewing? thanks

build bitcoin core from sources, add support for savefeeestimate sync, update tor

---

client/src/run-browser.js

The user's selection for language and theme will not get persisted, but everything else should work.
Fixes #366

Make localStorage optional

---

client/src/components/loading.js
client/src/views/addr.js
client/src/views/asset-list.js
client/src/views/asset.js
client/src/views/block.js
client/src/views/blocks.js
client/src/views/loading.js
client/src/views/transactions.js
www/style.css

**Update loading icon.**
- Change loading gif to css loading component.

Update loading icon

---

client/src/views/nav-toggle.js
flavors/blockstream/config.env
flavors/blockstream/extras.css

- Update Footer Date from 2022 - 2023
- Add Blog to Useful links (Hamburger) 
- Fix Blockstream Explorer logo UI bug

Change Footer Date

---

README.md

docs: Mention pre-built docker image in README

---

Dockerfile.deps

- update rust toolchain to match electrs pin of 1.75.0

Update electrs to 49a71805a2 and rust to 1.75.0

---

contrib/liquid-mainnet-explorer.conf.in

Improve esplora liquid mainnet propagation times.

liquid: addnode the seed bridges

---

client/src/views/lander.js
www/style.css

- added links to the dashboard
- updated pricing information

Update pricing copy on the Explorer API landing page

---

client/src/views/lander.js
www/style.css

update the request range copy for better clarity in the pricing section

update pricing section copy

---

client/src/app.js
client/src/util.js
client/src/views/tx.js

- when calculating overpayment, consider liquid transactions for which discount CT rates were or are available
- extract calculations for fee rates and overpayment into functions

extend overpayment warning to discountCT (liquid) txes

---

.github/workflows/start-gitlab.yml

Remember to actually pass it to the CURL

CI: patch follow-up
