- API.md
The api itself returns string:decimal pairs but the documentation example shows it as int:decimal.
This brings the documentation in line with the api.
Addresses Issue #87
> Amend example results of fee-estimates to string: decimal

- www/light-theme_style.css
Light Theme - Assets Table row text color update for Large Screen and Mobile
Assets list for light theme is unreadable
Steps to reproduce
On - https://blockstream.info/liquid/assets , switch to light mode.
**Current behaviour**
The text displays in white. 
**Desired behaviour**
Match the color with the main block list (black).
**Issue created in the link below**
https://gl.blockstream.com/greenaddress/esplora/-/issues/96
> Light Theme - Assets Table row text color update

- client/src/views/block.js
- client/src/views/home.js
- client/src/views/tx-vout.js
- client/src/views/tx.js
- client/src/views/util.js
**Improved numeric spacing**
Issue created by Allen
https://gl.blockstream.com/greenaddress/esplora/-/issues/99
- Remove Spacing and Commas from Main Block list
- Timestamp - relabel the header as the displayed timezone, e.g. TIMESTAMP (GMT -5), and each item should only display the date/time.
Transaction details:
* always display block height without a space or comma.
* amounts, always display 8 full decimals (unless 0).
> Improved numeric spacing

- www/style.css
**UI bug - Confidential Addresses Qr codes step over the header container #272**
- The Qr code for confidential addresses is larger and steps over the colored container, into the darker background
- Example address
https://blockstream.info/liquid/address/VJLCpZ8hvvCcmwz8doVqrd3bWRYJseXs5UykvNDGrXK175ovdNYzdQhzCkZz1Y5uc4KYmuNCgNKUDakx
**See Issue link below**
[Ticket Link on Github](https://github.com/Blockstream/esplora/issues/272)
> UI Bug - Confidential Addresses QR fixed

- contrib/liquid-mainnet-explorer.conf.in
- elementsd will mark liquid blocks as invalid, if they contain pegins
that reference mainchain blocks that haven't synced
- elementsd does not (yet) recover by itself, see
https://github.com/ElementsProject/elements/issues/891
- when elementsd can automatically revalidate blocks, we
should revert this commit
> Disable pegin validation to workaround mainchain sync delay

- .gitlab-ci.yml
- terraform/main.tf
- terraform/modules/prometheus/cloud-init/prometheus.yml
- terraform/modules/prometheus/data.tf
- terraform/modules/prometheus/main.tf
- terraform/modules/prometheus/variables.tf
- terraform/variables.tf
updates the prometheus config, removing things we no longer need (assumes a Prometheus federation) and makes the setup more stable.
> devops/tasks#1361: update prometheus federation

- Dockerfile.deps
- contrib/liquid-regtest-explorer.conf.in
- run.sh
- pass --jsonrpc-import to electrs for liquid regtest to workaround magic number changing
- when in liquid/regtest mode, create a wallet (elements 21 does not load a wallet by default)
> Update elements to 0.21.0

- Dockerfile.deps
- run.sh
- use jsonrpc-import for liquid-testnet to avoid chain binary incompatibilities
> Update electrs to latest tip

- API.md
Actually, all transactions returned by the endpoint /block/:hash/txs[/:start_index] contains status information even if it's the same block.
[block 170 txs](https://blockstream.info/api/block/00000000d1145790a8694403d4063f323d499e655c83426834d4ce2f8dd4a2ee/txs)
> Remove a piece of documentation that is not true

- Dockerfile.deps
- contrib/0001-add-support-to-save-fee-estimates-without-shutting-d.patch
- contrib/bitcoin-mainnet-explorer.conf.in
- contrib/bitcoin-regtest-explorer.conf.in
- contrib/bitcoin-signet-explorer.conf.in
- contrib/bitcoin-testnet-explorer.conf.in
Updates:
- bitcoin core to v24 (w/ rebased savefeeestimate patch)
- elements to 22.0.2
- rust to 1.65.0
- enable transaction replacement
> Update: bitcoin core to v24 (w/ rebased savefeeestimate patch), elements to 22.0.2, rust to 1.65.0, enable transaction replacement

- contrib/bitcoin-mainnet-explorer.conf.in
- contrib/bitcoin-regtest-explorer.conf.in
- contrib/bitcoin-signet-explorer.conf.in
- contrib/bitcoin-testnet-explorer.conf.in
Updates the bitcoind config templates to set `maxmempool` to 1000 MB
> bitcoind configs: set maxmempool to 1000 MB

- contrib/0001-add-support-to-save-fee-estimates-without-shutting-d.patch
- contrib/runit_boot.sh
Hello
I fixed some typos in the docs,
Hope it helps.
Br,
Tudor.
> fix: typos in the documentation

- client/src/app.js
Attempting to access the URL hash fragment (`location.hash`) on the server-side was causing an error, because it is not available there.
Unblinding should only be done on the client-side for privacy reasons anyway, so this feature can be disabled entirely on the server-side.
> Disable Elements unblinding in the server-side rendering environment

- client/src/run-server.js
- client/src/util.js
- client/src/views/error.js
Prior to this fix, `render()` preemptively considered the app rendering to be final, before completing the transition out of the loading state entirely.
This resulted in notFound pages not being identified as such, returning them with a 200 OK status code instead of a 404 Not Found.
> prerender: Wait for the loading state to complete, fix HTTP error status codes

- contrib/runit_boot.sh
This PR changes the order in which services are stopped when the docker container is shut down.
With the previous order (based on `ls` output) I was getting the following logs:
```
shutting down container
4-2024-02-01T22:07:20Z tor: Thread interrupt
4-2024-02-01T22:07:20Z Shutdown: In progress...
4-2024-02-01T22:07:20Z RemoveLocal(g4xk3jxhqac4qqexdrnhk2mnd4c6dnmufvt4mifkwiyipvq7xzj5i3qd.onion:18444)
4-2024-02-01T22:07:20Z opencon thread exit
4-2024-02-01T22:07:20Z torcontrol thread exit
4-2024-02-01T22:07:20Z addcon thread exit
4-2024-02-01T22:07:20Z net thread exit
4-2024-02-01T22:07:20Z msghand thread exit
2-2024-02-01T22:07:20.430+00:00 - WARN - reconnecting to bitcoind: failed to read cookie from "/data/bitcoin/regtest/.cookie"
2-2024-02-01T22:07:23.431+00:00 - WARN - failed to …
```
> fix docker service stop

- client/src/views/tx.js
Add UI display for Liquid discount_vsize and discount_weight fields.
Not visible in non liquid chains.
In liquid:
> liquid: add discount_vsize and discount_weight to tx display

- www/style.css
Prevent word breaking across lines
> reduce right margin for subnav links

- client/src/views/tx.js
Prior to this fix, some error types originating from the WASM runtime were not displayed properly.
> Explicitly convert unblinding errors to strings

- Dockerfile.deps
We can now use the latest libwally-core, following https://github.com/ElementsProject/libwally-core/pull/491 which allows to override `EMCC_OPTIONS` entirely.
The build target directory was also changed from `wally_dist` to just `dist`, in https://github.com/ElementsProject/libwally-core/commit/f4229b58c7d21e699c60983f7edb44266651a4e0#diff-099d172147ace15dd52979d57196e96d3c9dc8fa77f92fb9e216e1301600c35fL46-R46.
> docker: Update libwally-core to latest

- gitlab/test.yml
Cloning doesn't work yet, attempting to fix.
> CI: patch follow-up
